import { VaultItem } from '@/entrypoints/popup/types/vault';

export const dummyItems: VaultItem[] = [
  {
    id: '1',
    username: 'user1',
    password: 'pass1',
    domains: ['example.com'],
    updated: '2024-01-01T12:00:00Z',
  },
  {
    id: '2',
    username: 'user2',
    password: 'pass2',
    domains: ['example.org', 'example.net'],
    updated: '2024-02-01T12:00:00Z',
    notes: 'Some notes about this entry',
  },
  {
    id: '3',
    username: 'john.doe@gmail.com',
    password: 'SecurePass123!',
    domains: ['google.com', 'gmail.com'],
    updated: '2024-03-15T09:30:00Z',
  },
  {
    id: '4',
    username: 'jane_smith',
    password: 'MyP@ssw0rd',
    domains: ['github.com'],
    updated: '2024-04-20T14:45:00Z',
    notes: 'Work account',
  },
  {
    id: '5',
    username: 'admin@company.io',
    password: 'Admin#2024',
    domains: ['company.io', 'dashboard.company.io'],
    updated: '2024-05-10T11:00:00Z',
  },
  {
    id: '6',
    username: 'netflix_user',
    password: 'StreamingLife99',
    domains: ['netflix.com'],
    updated: '2024-06-05T18:20:00Z',
    notes: 'Family plan',
  },
  {
    id: '7',
    username: 'shopaholic22',
    password: 'BuyStuff!456',
    domains: ['amazon.com', 'amazon.co.uk'],
    updated: '2024-07-12T10:15:00Z',
  },
  {
    id: '8',
    username: 'dev@startup.tech',
    password: 'C0d3Master!',
    domains: ['gitlab.com'],
    updated: '2024-08-25T16:30:00Z',
    notes: 'Personal projects',
  },
  {
    id: '9',
    username: 'social_butterfly',
    password: 'Insta2024#',
    domains: ['instagram.com', 'facebook.com'],
    updated: '2024-09-08T20:00:00Z',
  },
  {
    id: '10',
    username: 'gamer_pro',
    password: 'G4m3rL1f3!',
    domains: ['steam.com', 'epicgames.com'],
    updated: '2024-10-30T22:45:00Z',
    notes: 'Gaming accounts',
  },
];
